# Site settings:
title: Han Kim
email: hankim [at] caltech [dot] edu
description: grad student
github_username: hanhanhan-kim
twitter_username: hanhanhan_kim

# Build settings:
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jemoji