# Site settings:
title: han kim
email: hankim [at] caltech [dot] edu
description: neuro grad student
logo: assets/headshot_circle.png

# Build settings:
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jemoji
  - jekyll-webp